export const COLOR_BIRTHDAY_LEAVE = '#D291BC';
export const COLOR_BEREAVEMENT_LEAVE = '#B0B0B0';
export const COLOR_EMERGENCY_LEAVE = '#E57373';
export const COLOR_SICK_LEAVE = '#E6A86D';
export const COLOR_VACATION_LEAVE = '#64B5F6';

export const CHART_COLORS = {
  COLOR_BIRTHDAY_LEAVE: COLOR_BIRTHDAY_LEAVE,
  COLOR_BEREAVEMENT_LEAVE: COLOR_BEREAVEMENT_LEAVE,
  COLOR_EMERGENCY_LEAVE: COLOR_EMERGENCY_LEAVE,
  COLOR_SICK_LEAVE: COLOR_SICK_LEAVE,
  COLOR_VACATION_LEAVE: COLOR_VACATION_LEAVE
};
